version: '3.8'

services:
  mariadb:
    image: mariadb
    container_name: my-mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: abc@123
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql