version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: abc@123
      MYSQL_PASSWORD: abc@123
      MYSQL_DATABASE: authen_system
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: