server:
  port: ":8083"

mysql:
  hostPort: "localhost:3306"
  username: "root"
  password: "abc@123"
  databaseName: "authen_system"
  maxIdleConnections: 5
  maxOpenConnections: 10
  connectionMaxLifetime: 3600

authentication:
  secretKey: "RCp1VZUYwnFbDo4fjN0Wd3pOIc6nlhmZpwqRzCrNXW4="