POST http://localhost:8083/api/v1/user/signup
Content-Type: application/json

{
  "fullName": "Nguyen Van K",
  "phoneNumber": "012345672222",
  "email": "cn12w@gmail.com",
  "userName": "cn12w",
  "password": "abc12@123",
  "birthday": "1998-01-01"
}

###
POST http://localhost:8083/api/v1/user/login
Content-Type: application/json

{
  "phoneNumber": "012345672222",
  "password": "abc12@123"
}

###
GET http://localhost:8083/api/v1/home
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDk4MTM0NDgsInN1YiI6IjEifQ.ZUeTfq4d-NaH7v4-BDsA6XQ35hIDSbUJj_MX6ilrAvM